control:
  host: 127.0.0.1
  port: 8001
  db:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: ""
    database: portkey
    sslmode: disable

data:
  host: 127.0.0.1
  port: 8080
  control_url: http://127.0.0.1:8001
  redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    db: 0

logging:
  level: info
  development: true
